SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
AND I.SEX_UPON_INTAKE like 'Intact%'
AND O.SEX_UPON_OUTCOME not like 'Intact%'
ORDER BY I.ANIMAL_ID
